### ISSUE TITLE
[BUG] Problem running PRTF

### ISSUE THREAD

**Issue by DSimonne** [carnisj/bcdi#267]
Hi,

I tried to use the PRTF script in the package, but I have the following error in xrayutilities:

```python
hpc5-1102:david/SIXS_June_2021/PRTF % python PRTF.py 
#########
Scan 3572
#########

##############
Setup instance
##############
Setup(beamline_name="SIXS_2019", detector_name="Merlin", beam_direction=[1.0, 0.0, 0.0], energy=8500, distance=1.18, outofplane_angle=None, inplane_angle=None, tilt_angle=None, rocking_angle="inplane", grazing_angle=None, )

#################
Detector instance
#################
Merlin(name="Merlin", rootdir="./", datadir="./S3572/data/", savedir="./", template_file=None, template_imagefile="B12_syn_S1_P1_300C_ascan_mu_%05d.nxs", specfile="/gpfs/easy/data/id01/inhouse/david/rnice.env/lib/python3.8/site-packages/bcdi/preprocessing/alias_dict_2021.txt", sample_name="S", roi=[0, 515, 0, 515], sum_roi=[0, 515, 0, 515], binning=(1, 1, 1), )
Pixel sizes after phasing_binning (vertical, horizontal):  5.5e-05 5.5e-05 (m)

Measured data shape = 180, 360, 400, Max(measured amplitude)=488.3
COM of measured pattern after masking: 90.01, 179.23, 199.88
refined COM: 90, 179, 201, Number of unmasked photons = 75563540

### ReadNxs3 ###
### End of ReadNxs3 ###

Traceback (most recent call last):
  File "PRTF.py", line 443, in <module>
    qx, qz, qy, _ = setup.calc_qvalues_xrutils(
  File "/gpfs/easy/data/id01/inhouse/david/rnice.env/lib/python3.8/site-packages/bcdi/experiment/setup.py", line 724, in calc_qvalues_xrutils
    qx, qy, qz = hxrd.Ang2Q.area(
  File "/gpfs/easy/data/id01/inhouse/david/rnice.env/lib/python3.8/site-packages/xrayutilities/experiment.py", line 1051, in area
    raise InputError("QConversion: wrong amount (%d) of arguments "
xrayutilities.exception.InputError: QConversion: wrong amount (4) of arguments given, number of arguments should be 5
hpc5-1102:david/SIXS_June_2021/PRTF % 
```

The files are here:
/data/id01/inhouse/david/SIXS_June_2021/PRTF/

The same script is used in strain.py, so not sure why it does not work here...
Any idea ?

**Comment by DSimonne** [comment]
It's the right version of xrayutilities

**Comment by carnisj** [comment]
Where does this script comes from? In the package we have `bcdi_prtf_BCDI.py`. I should check once that it still works, though

**Comment by DSimonne** [comment]
Yes it comes from there =)

**Comment by carnisj** [comment]
The scritp works for a dataset from CRISTAL, something might be wrong with the pipeline for SIXS

**Comment by carnisj** [comment]
Found it, the angle beta (diffractometer incident angle) is below both sample and detector, but is provided only one time in the call to `hxrd.Ang2Q.area`. I will fix that.

**Comment by carnisj** [comment]
can you test with the branch `bug_prtf`?

**Comment by DSimonne** [comment]
The script works !

It gives me this:

```python
2021/PRTF % python PRTF.py 
#########
Scan 3572
#########

##############
Setup instance
##############
Setup(beamline_name="SIXS_2019", detector_name="Merlin", beam_direction=[1.0, 0.0, 0.0], energy=8500, distance=1.18, outofplane_angle=None, inplane_angle=None, tilt_angle=None, rocking_angle="inplane", grazing_angle=None, )

#################
Detector instance
#################
Merlin(name="Merlin", rootdir="./", datadir="./S3572/data/", savedir="./", template_file=None, template_imagefile="B12_syn_S1_P1_300C_ascan_mu_%05d.nxs", specfile="/gpfs/easy/data/id01/inhouse/david/p9.dev/lib/python3.8/site-packages/bcdi/preprocessing/alias_dict_2021.txt", sample_name="S", roi=[0, 515, 0, 515], sum_roi=[0, 515, 0, 515], binning=(1, 1, 1), )
Pixel sizes after phasing_binning (vertical, horizontal):  5.5e-05 5.5e-05 (m)

Measured data shape = 180, 360, 400, Max(measured amplitude)=488.3
COM of measured pattern after masking: 90.01, 179.23, 199.88
refined COM: 90, 179, 201, Number of unmasked photons = 75563540

### ReadNxs3 ###
### End of ReadNxs3 ###

COM[qx, qz, qy] = 0.00, 0.02, 2.76
Opening  S3572/preprocessing/modes_gui.h5
Max(retrieved amplitude) = 1411.6
COM of the retrieved diffraction pattern after masking: 89.24, 179.88, 199.85

Normalizing the phased data to the sqrt of the measurement at the center of mass of the diffraction pattern ...
Normalization factor = 0.3459

Distance max: 0.07(1/A) at: (0, 0, 399)
PRTF.py:713: RuntimeWarning: Mean of empty slice.
  prtf_avg[index] = temp[~np.isnan(temp)].mean()
q resolution = 0.11950 (1/nm)
resolution d = 52.6 nm
(p9.dev) p9-01:david/SIXS_June
```

![image](https://user-images.githubusercontent.com/51970962/173229512-f238ec7b-9cfd-42a0-9f6d-81e40c70ed01.png)

**Comment by carnisj** [comment]
Great, can you review the pull request?
